# 服务器端口配置
server:
  port: 8080

# 数据库配置、配置文件选择
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_demo?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  profiles:
    active: dev
  # 配置 webapp 和 jsp
  mvc:
    view:
      prefix: /view/
      suffix: .jsp

# 配置 MyBatis 配置路径
mybatis:
  mapper-locations: classpath:mybatis/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置，配置打印 mybatis 执行的 sql
logging:
  level:
    org:
      example:
        orderdemo: debug