# 文件地址映射
local-directory: E:\MyUniversity\0_ProgrammingLearning\springboot_program\myoj-ssm\tmp\files\

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myoj?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

logging:
  level:
    org:
      example:
        myojssm: debug
