# 文件地址映射
local-directory: /root/myoj/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myoj?characterEncoding=utf8&useSSL=false
    username: myoj
    password: 7LpxR8hMRE3R6aFA
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
