# 自定义配置
jwt:
  header-key: Authorization #TOKEN_HEADER_KEY JWT请求头KEY

# SpringBoot配置
server:
  port: 8080

spring:
  profiles:
    active: dev
  # 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 阿里云OSS配置
aliyun:
  oss:
    # 地域节点
    end-point: https://oss-cn-hangzhou.aliyuncs.com
    # OSS的Bucket名称
    bucket-name: lyyoj
    # Bucket 域名
    url-prefix: https://lyyoj.oss-cn-hangzhou.aliyuncs.com/
    # 目标文件夹
    file-host: avatar/

