spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
  mail:
    host: smtp.qq.com
    username: liaoyueyue.email@qq.com
    password: ipkphrqvhwokbebi
    default-encoding: utf-8

# 日志配置，配置打印 mybatis 执行的 sql
logging:
  level:
    com:
      example:
        myblogssm: debug