# 服务器端口配置
server:
  port: 8081
  servlet:
    session:
      timeout: 1800

# 配置文件选择
spring:
  profiles:
    active: dev
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  servlet:
    multipart:
#      location: ${user.dir}/temp # 设置上传的临时目录
      max-file-size: 10MB # 设置支持的单个上传文件的大小限制
      max-request-size: 10MB # 设置最大的请求文件大小，设置总体大小请求
  mail:
    host: smtp.163.com
    username: a973044869@163.com
    password: EE7BpxeFakzpymjW
    default-encoding: utf-8

# 配置 MyBatis 配置路径
mybatis:
  mapper-locations: classpath:mybatis/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl