spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?characterEncoding=utf8&useSSL=false
    username: myblog
    password: xBs547kiszh7kpxn
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
  mail:
    host: smtp.163.com
    port: 465 #端口号 465 或 587
    username: a973044869@163.com
    password: EE7BpxeFakzpymjW
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
